grocery_app/models.py
from sqlalchemy_utils import URLType

from grocery_app.extensions import db
from grocery_app.utils import FormEnum

class ItemCategory(FormEnum):
    """Categories of grocery items."""

    PRODUCE = 'Produce'
    DELI = 'Deli'
    BAKERY = 'Bakery'
    PANTRY = 'Pantry'
    FROZEN = 'Frozen'
    OTHER = 'Other'

class GroceryStore(db.Model):
    """Grocery Store model."""

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(80), nullable=False)
    address = db.Column(db.String(200), nullable=False)
    items = db.relationship('GroceryItem', back_populates='store')

    def __str__(self):
        return f"<Store: {self.title}>"

    def __repr__(self):
        return f"<Store: {self.title}>"

class GroceryItem(db.Model):
    """Grocery Item model."""
    
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    price = db.Column(db.Float(precision=2), nullable=False)
    category = db.Column(db.Enum(ItemCategory), default=ItemCategory.OTHER)
    photo_url = db.Column(URLType)
    store_id = db.Column(
        db.Integer, db.ForeignKey('grocery_store.id'), nullable=False)
    store = db.relationship('GroceryStore', back_populates='items')

    def __str__(self):
        return f"<Item: {self.name}>"

    def __repr__(self):
        return f"<Item: {self.name}>"

grocery_app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, DateField, SelectField, SubmitField,FloatField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.validators import DataRequired, Length, URL
from grocery_app.models import ItemCategory, GroceryStore


class GroceryStoreForm(FlaskForm):
    """Form for adding/updating a GroceryStore."""

    title = StringField(
        "Store Title", validators=[DataRequired(), Length(min=3, max=80)]
    )
    address = StringField(
        "Store Address", validators=[DataRequired(), Length(min=3, max=200)]
    )
    submit = SubmitField("Submit")


class GroceryItemForm(FlaskForm):
    """Form for adding/updating a GroceryItem."""

    name = StringField("Item Name", validators=[DataRequired(), Length(min=3, max=80)])
    price = FloatField("Item Price", validators=[DataRequired()])
    category = SelectField("Category", choices=ItemCategory.choices())
    photo_url = StringField("Item Photo URL", validators=[URL(require_tld=True)])
    store = QuerySelectField("Stores", query_factory=lambda: GroceryStore.query)
    submit = SubmitField("Submit")

grocery_app/routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from datetime import date, datetime
from grocery_app.models import GroceryStore, GroceryItem
from grocery_app.forms import GroceryStoreForm, GroceryItemForm

# Import app and db from events_app package so that we can run app
from grocery_app.extensions import app, db

main = Blueprint("main", __name__)

##########################################
#           Routes                       #
##########################################

@main.route("/")
def homepage():
    all_stores = GroceryStore.query.all()
    print(all_stores)
    return render_template("home.html", all_stores=all_stores)


@main.route("/new_store", methods=["GET", "POST"])
def new_store():
    form = GroceryStoreForm()
    if form.validate_on_submit():
        new_store = GroceryStore(title=form.title.data, address=form.address.data)
        db.session.add(new_store)
        db.session.commit()
        flash("New store was created successfully. Yayy!")
        return redirect(url_for("main.store_detail", store_id=new_store.id))
    return render_template("new_store.html", form=form)


@main.route("/new_item", methods=["GET", "POST"])
def new_item():
    form = GroceryItemForm()
    if form.validate_on_submit():
        new_item = GroceryItem(
            name=form.name.data,
            price=form.price.data,
            category=form.category.data,
            photo_url=form.photo_url.data,
            store=form.store.data,
        )
        db.session.add(new_item)
        db.session.commit()
        flash("New Item was created successfully. Yayy!")
        return redirect(url_for("main.item_detail", item_id=new_item.id))

    return render_template("new_item.html", form=form)


@main.route("/store/<store_id>", methods=["GET", "POST"])
def store_detail(store_id):
    store = GroceryStore.query.get(store_id)
    form = GroceryStoreForm(obj=store)
    if form.validate_on_submit():
        store.title = form.title.data
        store.address = form.address.data
        db.session.add(store)
        db.session.commit()
        flash("Store was updated successfully.")
        return redirect(url_for("main.store_detail", store_id=store_id))

    return render_template("store_detail.html", store=store, form=form)


@main.route("/item/<item_id>", methods=["GET", "POST"])
def item_detail(item_id):
    item = GroceryItem.query.get(item_id)
    form = GroceryItemForm(obj=item)
    if form.validate_on_submit():
        item.name = form.name.data
        item.price = form.price.data
        item.category = form.category.data
        item.photo_url = form.photo_url.data
        item.store = form.store.data
        db.session.add(item)
        db.session.commit()
        flash("Item was updated successfully. Yayy!")
        return redirect(url_for("main.item_detail", item_id=item_id))
    return render_template("item_detail.html", item=item, form=form)

grocery_app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Grocery Store Tracker</title>
        <link rel="stylesheet" href="/static/style.css">
        <!-- <link rel="stylesheet" href="/static/styles.css"> -->
    </head>
    <body>
        <div id="content">
            {% for message in get_flashed_messages() %}
                <p>{{ message }}</p>
            {% endfor %}
            <nav>
                <a href="/">Home</a>
                <div>
                    <a href="/new_store">New Store</a>
                    <a href="/new_item">New Item</a>
                </div>
            </nav>
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

grocery_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Grocery Store Tracker</h1>

<p><em>The best place to track prices and find the hottest deals!</em></p>

<h2>All Stores</h2>

{% for store in all_stores %}
<div class="store">
    <a href="/store/{{ store.id }}">{{ store.title }}</a> - 
    {{ store.items|length }} items
    <p><strong>Address:</strong> {{ store.address }}</p>
</div>
{% endfor %}

{% endblock %}

grocery_app/templates/item_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Item - {{ item.name }}</h1>

<p><img src="{{ item.photo_url }}" width="250px" height="250px"></p>

<p><strong>Price:</strong> {{ item.price }}</p>

<p><strong>Category:</strong> {{ item.category }}</p>

<p><strong>Store:</strong> {{ item.store.title }}</p>


<h2>Edit Item</h2>

<form method="POST" action="{{ url_for('main.item_detail', item_id=item.id) }}">
    <fieldset>
        <legend>Please enter your information:</legend>
        {{ form.name.label }}
        {{ form.name }}
        {{ form.price.label }}
        {{ form.price }}
        {{ form.category.label }}
        {{ form.category }}
        {{ form.photo_url.label }}
        {{ form.photo_url }}
        {{ form.store.label }}
        {{ form.store }}
        <input type="submit" value="Submit">
    </fieldset>
</form>

{% endblock %}

grocery_app/templates/new_item.html
{% extends 'base.html' %}
{% block content %}

<h1>New Item</h1>

<form method="POST" action="{{url_for('main.new_item')}}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Please enter your information:</legend>
            {{ form.name.label }}
            {{ form.name }}
            {{ form.price.label }}
            {{ form.price }}
            {{ form.category.label }}
            {{ form.category }}
            {{ form.photo_url.label }}
            {{ form.photo_url }}
            {{ form.store.label }}
            {{ form.store }}
        <input type="submit" value="Submit">
    </fieldset>
</form>


{% endblock %}

grocery_app/templates/new_store.html
{% extends 'base.html' %}
{% block content %}

<h1>New Store</h1>

<form method="POST" action="{{ url_for('main.new_store') }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Please enter your information:</legend>
            {{ form.title.label }}
            {{ form.title }}
            {{ form.address.label }}
            {{ form.address }}
            {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

grocery_app/templates/store_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Store - {{ store.title }}</h1>

<strong>Address:</strong> {{ store.address }}

<h2>Items</h2>

<div class="items">
    {% for item in store.items %}
    <div class="item-details">
        <a href="/item/{{ item.id }}"><img src="{{ item.photo_url }}" alt="{{ item.name }}" width="200px">
        <p><strong>{{ item.name }}</strong></p></a>
        <p><strong>Price: ${{ item.price }}</strong></p>
    </div>
    {% endfor %}
</div>


<h2>Edit Store</h2>

<form method="POST" action="{{ url_for('main.store_detail', store_id=store.id) }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Please enter your information:</legend>
        {{ form.title.label }}
        {{ form.title }}
        {{ form.address.label }}
        {{ form.address }}
        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}